apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudsearch-ingestion
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: ingestion
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: "2"
              memory: 2Gi
