apiVersion: v1
kind: Service
metadata:
  name: cloudsearch-frontend
  labels:
    app.kubernetes.io/name: cloudsearch-frontend
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: cloudsearch
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: cloudsearch-frontend
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
