apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloudsearch

resources:
  - namespace/namespace.yaml
  - api
  - ingestion
  - frontend

commonLabels:
  app.kubernetes.io/part-of: cloudsearch
  app.kubernetes.io/managed-by: kustomize
