apiVersion: v1
kind: Service
metadata:
  name: cloudsearch-ingestion
  labels:
    app.kubernetes.io/name: cloudsearch-ingestion
    app.kubernetes.io/component: ingestion
    app.kubernetes.io/part-of: cloudsearch
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: cloudsearch-ingestion
  ports:
    - name: health
      port: 8081
      targetPort: health
      protocol: TCP
